enum RideStatusEnum {
  REQUEST_SENT = 'REQUEST SENT',
  ACCEPTED = 'ACCEPTED',
  ON_THE_WAY = 'ON THE WAY',
  IN_PROGRESS = 'IN PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export default RideStatusEnum;
